Repository dreamwidth/dreamwidth, pull requests merged in 2018-06, with the labels that each got.

#2344 Add Audiomax, chirb.it and Mixstep to whitelist
  cgi-bin/DW/Hooks/EmbedWhitelist.pm
  t/embed-whitelist.t
Labels: status: untriaged

#2343 Removes awkward beta update whitespace if no icons
  views/entry/module-icons.tt
Labels: status: untriaged

#2342 Add LJ to Other Sites for profile
  bin/upgrading/proplists.dat
  cgi-bin/DW/Logic/ProfilePage.pm
  htdocs/img/profile_icons/livejournal.gif
  htdocs/manage/profile/index.bml
  htdocs/manage/profile/index.bml.text
  htdocs/profile.bml.text
Labels: effort: (1) lower, review: requested changes

#2341 Add box.com, lichess and MSNBC to embed whitelist
  cgi-bin/DW/Hooks/EmbedWhitelist.pm
  t/embed-whitelist.t
Labels: effort: (1) lower, is: feature, review: requested changes

#2346 Add Funny or Die to embeds whitelist
  cgi-bin/DW/Hooks/EmbedWhitelist.pm
  t/embed-whitelist.t
Labels: status: untriaged

#2347 Prevent creation of access filter names with commas
  htdocs/manage/circle/editfilters.bml
  htdocs/manage/circle/editfilters.bml.text
Labels: status: untriaged

#2345 Allow email spell-checking to be overridden
  cgi-bin/DW/Controller/Admin/SupportCat.pm
  cgi-bin/DW/Controller/ChangeEmail.pm
  cgi-bin/DW/Controller/Create.pm
  cgi-bin/DW/Controller/Support/Submit.pm
  cgi-bin/DW/Setting/ProfileEmail.pm
  cgi-bin/DW/Shop/Item.pm
  cgi-bin/LJ/Console/Command/EmailAlias.pm
  cgi-bin/LJ/HTMLControls.pm
  cgi-bin/LJ/Sysban.pm
  cgi-bin/LJ/User/Message.pm
  cgi-bin/LJ/Widget/ShopItemOptions.pm
  htdocs/admin/sysban.bml
  htdocs/manage/circle/invite.bml
  htdocs/manage/profile/index.bml
  htdocs/shop/account.bml
  htdocs/shop/confirm.bml
  htdocs/support/append_request.bml
  htdocs/tools/tellafriend.bml
  t/check-email.t
  views/admin/supportcat/category.tt
  views/changeemail.tt
  views/create/account.tt
  views/support/request/form.tt
  views/support/submit.tt
Labels: status: untriaged

#2348 Remove Imzy from Other Sites
  bin/upgrading/proplists.dat
  cgi-bin/DW/External/Site/Imzy.pm
  cgi-bin/DW/Logic/ProfilePage.pm
  htdocs/img/external/imzy.png
  htdocs/manage/profile/index.bml
  htdocs/manage/profile/index.bml.text
  htdocs/profile.bml.text
Labels: effort: (1) lower, is: bug, review: requested changes

#2349 Clarify Support "No HTML allowed" messages
  htdocs/support/act.bml
  htdocs/support/act.bml.text
  htdocs/support/see_request.bml.text
  views/support/request/form.tt
  views/support/submit.tt
  views/support/submit.tt.text
Labels: status: untriaged
